@Backend_HostAddress = http://localhost:9002

POST {{Backend_HostAddress}}/api/login
Content-Type: application/json

{
  "Username": "Aneta",
  "Password": "haslo"
}

> {% client.global.set("auth_token_user", response.body.token); %}

###
POST {{Backend_HostAddress}}/api/login
Content-Type: application/json

{
  "Username": "Bartek",
  "Password": "Password"
}

> {% client.global.set("auth_token_admin", response.body.token); %}

###
GET {{Backend_HostAddress}}/api/user/0
Authorization: Bearer {{auth_token_user}}

###
GET {{Backend_HostAddress}}/api/user/1
Authorization: Bearer {{auth_token_user}}

###
GET {{Backend_HostAddress}}/api/user/0
Authorization: Bearer {{auth_token_admin}}

###
GET {{Backend_HostAddress}}/api/user/1
Authorization: Bearer {{auth_token_admin}}

###
POST {{Backend_HostAddress}}/api/logs
Authorization: Bearer {{auth_token_admin}}